[build]
  command = "react-scripts build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "react-scripts start"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/"
  status = 200