[build]
  command = "react-scripts build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "react-scripts start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/"
  status = 200